/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `version-catalog`
    `maven-publish`
}

group = "com.saurabhsandav"
version = "0.0.4"

catalog {
    // declare the aliases, bundles and versions in this block
    versionCatalog {
        from(files("$projectDir/src/libs.versions.toml"))
    }
}

publishing {

    repositories {
        maven {
            name = "CommonVersions"
            url = uri("https://maven.pkg.github.com/saurabhsandav/CommonVersions")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }

    publications {
        create<MavenPublication>("maven") {
            artifactId = "common-versions"
            from(components["versionCatalog"])
        }
    }
}
