[versions]
kotlin = "1.6.10"
coroutines = "1.6.0"
serialization = "1.3.2"
android = "7.0.4"
activity = "1.5.0-alpha01"
media3 = "1.0.0-alpha01"
sqldelight = "1.5.3"
ktor = "2.0.0-beta-1"
multiplatform-settings = "0.8.1"
ksp = "1.6.10-1.0.2"
kotlin-inject = "0.4.1"
common = "0.1.0"

[plugins]
gradle-versions-checker = "com.github.ben-manes.versions:0.42.0"

android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

kotlinx-binaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.8.0"

jetbrains-compose = "org.jetbrains.compose:1.1.0-alpha03"

sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"

activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"

media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }

camerax-camera2 = "androidx.camera:camera-camera2:1.1.0-beta01"
camerax-lifecycle = "androidx.camera:camera-lifecycle:1.1.0-beta01"
camerax-view = "androidx.camera:camera-view:1.0.0-alpha32"

accompanist-insets = "com.google.accompanist:accompanist-insets:0.23.0"

mlkit-barcodeScanning = "com.google.android.gms:play-services-mlkit-barcode-scanning:18.0.0"

sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-androidDriver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-sqliteDriver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-coroutinesExtensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

okhttp = "com.squareup.okhttp3:okhttp:4.9.3"

ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

multiplatformSettings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatformSettings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatform-settings" }

kermit = "co.touchlab:kermit:1.0.3"

bundlizer = "dev.ahmedmourad.bundlizer:bundlizer-core:0.6.0"

coil-compose = "io.coil-kt:coil-compose:2.0.0-alpha07"

whatTheStack = "com.github.haroldadmin:WhatTheStack:1.0.0-alpha03"

kotlinInject-compilerKsp = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlin-inject" }
kotlinInject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlin-inject" }

common-core = { module = "com.saurabhsandav.common:compose", version.ref = "common" }
common-compose = { module = "com.saurabhsandav.common:compose", version.ref = "common" }
