name: Publish release (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish package
        run: ./gradlew -Pversion=${{ github.event.inputs.version }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
