name: Publish release (Auto)

on:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  publish-release:
    if: ${{ github.event.pull_request.merged && !contains( github.event.pull_request.labels.*.name, 'norelease') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.previoustag.outputs.tag }}
          version-fragment: 'feature'

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.bump_version.outputs.next-version }}
          title: ${{ steps.bump_version.outputs.next-version }}
          prerelease: false

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -Pversion=${{ steps.bump_version.outputs.next-version }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
